### PR TITLE
Add azimuth and incidence angle to shr_orb_mod

### LINKED ISSUE #10: Add new functions to shr_orb
Moving over from cime:
Add new functions to shr_orb to calculate azimuth and incidence angles. This is needed for the CTSM hillslope model.

**https://github.com/ESMCI/cime/issues/3700**

### PR DESCRIPTION
**Pull request by swensosc**
Add two routines to shr_orb_mod to enable calculation of azimuth angle and local incidence angle.
This is needed for the CTSM hillslope model.
Fixes #10

### CODE REVIEW

**Comment by mvertens** [comment]
@swensosc - can you clarify in the PR if this is expected to be bit-for-bit and what testing you did. I am not sure why the sripts regression tests are failing for this. @fischer, @jedwards - can you please look into the failure of the github actions scripts regression tests. It looks like its not finding the testlist.

**Comment by fischer-ncar** [comment]
I'm looking into the test failures.  Not sure what's going on yet.

**Comment by fischer-ncar** [comment]
@swensosc I've fixed the github actions scripts regression tests.  So if you merge main into your PR, the checks should pass.

**Comment by jedwards4b** [comment]
What is the current status of this PR?  Should it be merged or closed without merging?

**Comment by swensosc** [comment]
I do not know of a reason why it should be closed; I think it should be
merged.

**Comment by jedwards4b** [comment]
@fischer-ncar @mvertens any reason not to merge this now?

**Review by jedwards4b — APPROVED** [review]

**Pull request merged**
