### PR TITLE
Bug fix for fire emissions

### PR DESCRIPTION
**Pull request by fvitt**
This fixes an issue with how coefficients are applied to individual fire components.  This requires a change to CTSM code.

### CODE REVIEW

**Comment by ekluzek** [comment]
@fvitt it looks like this one has conflicts that have to be resolved. Could you update it to the latest CESM?

**Comment by ekluzek** [comment]
@fvitt this looks like the PR for CAM, let me know if I got it wrong.

https://github.com/ESCOMP/CAM/pull/452

**Comment by fvitt** [comment]
@ekluzek: For the latest cesm (cesm2_3_beta07) see https://github.com/ESCOMP/CMEPS/pull/265

**Comment by ekluzek** [comment]
@fischer-ncar we need to start making tags of the fire-emission changes to have a complete set of them to become a CESM tag. Can you merge this in and make a tag of it? Thanks.

**Comment by fischer-ncar** [comment]
@fvitt, can you resolve the conflicts for shr_fire_emis_mod.F90?

**Comment by fvitt** [comment]
Looks like the this code file moved to 

https://github.com/ESCOMP/CMEPS/blob/master/cesm/nuopc_cap_share/shr_fire_emis_mod.F90

**Comment by mvertens** [comment]
@fischer - this code is no longer in share - its in the nuopc cmeps code base. I'm confused as to why we are getting a conflict right now.

**Pull request closed without merging**
