### PR TITLE
add a logical function to determine if year is leap year

### PR DESCRIPTION
**Pull request by jedwards4b**
Add a test to see if the current year is a leap year.

### CODE REVIEW

**Comment by billsacks** [comment]
Thanks a lot for your work on this, @jedwards4b . What would you think about replacing the equality logic in shr_cal_leapyear with the use of 'mod', checking if mod(yr, 4) == 0, etc.? It seems like the equality comparisons could be prone to roundoff error with some compilers, at least for large years. I'm not sure if mod or modulo is the right function to use here: their behavior differs for negative numbers, which may be irrelevant since I don't think we can have a negative year in CESM(???).

**Comment by jedwards4b** [comment]
@billsacks after considerable thought I realized that no new logic that we can introduce will handle all of the possible edge cases that I have documented [here](https://github.com/ESCOMP/CDEPS/pull/191).

**Comment by billsacks** [comment]
@jedwards4b - I really appreciate you carefully thinking through these edge cases. I'm not seeing how that relates to the comment I made, though. I'm just suggesting replacing conditionals like `if (real(yr)/4.0 == yr/4)` – which seem like you're effectively trying to check if yr mod 4 == 0 – with the actual mod operator, which seems equivalent but not prone to roundoff errors. Maybe I'm missing something here, though.

**Comment by jedwards4b** [comment]
I see now, sorry.

**Comment by billsacks** [comment]
Looks good, thanks!

**Review by billsacks — APPROVED** [review]

**Pull request merged**
